import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CircleMinus, CirclePlus } from "lucide-react";
import { MarketingShell } from "@/components/marketing/site-shell";
import { marketingFaqs } from "@/lib/marketing-content";

export const metadata: Metadata = { title: "Frequently asked questions", description: "Clear answers about CloudInvoice, GST-ready invoices, payment links, UPI QR codes, Stripe payment tracking, client management, and product availability.", alternates: { canonical: "/faq" } };

export default function FaqPage() { return <MarketingShell><main className="marketing-noise"><section className="mx-auto max-w-5xl px-5 py-20 sm:py-28"><p className="marketing-eyebrow">CLOUDINVOICE FAQ</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.05em] text-white sm:text-6xl">Useful answers, before you need to ask twice.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-400">Everything currently available in CloudInvoice, explained without inflated product claims.</p><div className="mt-14 space-y-3">{marketingFaqs.map((faq, index) => <details key={faq.question} className="group rounded-2xl border border-white/[.08] bg-white/[.025] p-5 open:bg-white/[.04]"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-semibold text-white"><span><span className="mr-3 font-mono text-xs text-violet-300">{String(index + 1).padStart(2, "0")}</span>{faq.question}</span><span className="grid size-7 shrink-0 place-items-center rounded-full border border-white/[.1] text-zinc-400"><CirclePlus className="size-4 group-open:hidden" /><CircleMinus className="hidden size-4 group-open:block" /></span></summary><p className="mt-5 max-w-3xl pl-0 text-sm leading-7 text-zinc-400 sm:pl-8">{faq.answer}</p></details>)}</div><div className="mt-14 rounded-2xl border border-violet-300/15 bg-violet-400/[.07] p-7 text-center"><h2 className="text-xl font-semibold text-white">Ready to see it in your own workflow?</h2><p className="mt-2 text-sm text-zinc-400">Create a workspace and make the first invoice when you are ready.</p><Link href="/sign-in" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-zinc-950">Get started <ArrowRight className="size-4" /></Link></div></section></main></MarketingShell>; }
