"use client";

import { motion, AnimatePresence } from "motion/react";
import { BarChart3, CreditCard, FileText, LayoutDashboard, QrCode, Send, Sparkles } from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/utils";

const tabs = [
  { id: "dashboard", label: "Command center", icon: LayoutDashboard },
  { id: "invoice", label: "Invoice builder", icon: FileText },
  { id: "payments", label: "Payment portal", icon: CreditCard },
  { id: "analytics", label: "Analytics", icon: BarChart3 }
] as const;
type Tab = (typeof tabs)[number]["id"];

function DashboardView() { return <div className="grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-white/10 bg-black/30 p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-white">Good morning, Studio North</p><p className="mt-1 text-xs text-zinc-500">Here’s what moved today.</p></div><span className="rounded-lg border border-white/10 bg-white/5 px-2.5 py-1 text-xs text-zinc-400">July 2026</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[{ label: "Collected", value: "₹2,84,500", trend: "+18.4%" }, { label: "Outstanding", value: "₹46,280", trend: "8 invoices" }, { label: "Clients", value: "42", trend: "+5 this month" }].map((item) => <div key={item.label} className="rounded-xl border border-white/[.08] bg-white/[.035] p-3"><p className="text-[11px] font-medium text-zinc-500">{item.label}</p><p className="mt-2 text-lg font-semibold tracking-tight text-white">{item.value}</p><p className="mt-1 text-[11px] text-emerald-400">{item.trend}</p></div>)}</div><div className="mt-6 rounded-xl border border-white/[.08] bg-white/[.025] p-4"><div className="flex items-end justify-between"><div><p className="text-xs font-medium text-zinc-400">Cash collected this week</p><p className="mt-2 text-2xl font-semibold text-white">₹74,800</p></div><p className="text-xs font-semibold text-emerald-400">+12.8%</p></div><div className="mt-6 flex h-20 items-end gap-2">{[25, 42, 30, 62, 46, 73, 59, 88, 67, 82, 100, 78].map((height, index) => <motion.span key={index} initial={{ height: 0 }} animate={{ height: `${height}%` }} transition={{ delay: index * .035, duration: .35 }} className="flex-1 rounded-t bg-gradient-to-t from-violet-600 to-indigo-300/90" />)}</div></div></div><div className="grid gap-4"><div className="rounded-2xl border border-violet-400/20 bg-gradient-to-br from-violet-500/15 to-indigo-500/5 p-5"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-xl bg-violet-400/15 text-violet-200"><Sparkles className="size-4" /></span><span className="text-xs text-zinc-500">This month</span></div><p className="mt-5 text-sm text-zinc-400">Collection rhythm</p><p className="mt-1 text-3xl font-semibold text-white">89%</p><p className="mt-2 text-xs leading-5 text-zinc-400">Invoices are being paid within their terms.</p></div><div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><p className="text-xs font-semibold text-zinc-400">Next action</p><div className="mt-4 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-amber-400/10 text-amber-300"><Send className="size-4" /></span><div><p className="text-sm font-medium text-white">Follow up on INV-00042</p><p className="mt-1 text-xs text-zinc-500">Due tomorrow · ₹56,640</p></div></div></div></div></div>; }

function InvoiceView() { return <div className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center justify-between border-b border-white/[.08] pb-4"><div><p className="text-sm font-semibold text-white">New invoice</p><p className="mt-1 text-xs text-zinc-500">Draft · INV-00043</p></div><span className="rounded-lg bg-violet-400/10 px-2.5 py-1 text-xs font-medium text-violet-200">Modern template</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/[.08] p-3"><p className="text-[11px] text-zinc-500">Bill to</p><p className="mt-2 text-sm font-medium text-white">Acme Technologies</p><p className="mt-1 text-xs text-zinc-500">GSTIN 27ABCDE1234F1Z5</p></div><div className="rounded-xl border border-white/[.08] p-3"><p className="text-[11px] text-zinc-500">Due date</p><p className="mt-2 text-sm font-medium text-white">18 Aug 2026</p><p className="mt-1 text-xs text-zinc-500">In 14 days</p></div></div><div className="mt-5 space-y-2"><div className="grid grid-cols-[1fr_70px_100px] gap-3 px-2 text-[10px] font-bold uppercase tracking-[.12em] text-zinc-600"><span>Description</span><span>Qty</span><span className="text-right">Amount</span></div>{[["Product design retainer", "1", "₹48,000"], ["GST · 18%", "", "₹8,640"]].map(([description, quantity, amount]) => <div key={description} className="grid grid-cols-[1fr_70px_100px] gap-3 rounded-lg border border-white/[.06] bg-black/20 px-3 py-3 text-sm"><span className="text-zinc-200">{description}</span><span className="text-zinc-500">{quantity}</span><span className="text-right font-medium text-white">{amount}</span></div>)}</div></div><div className="rounded-2xl border border-violet-400/20 bg-violet-500/[.07] p-5"><p className="text-xs font-semibold text-violet-200">LIVE TOTAL</p><p className="mt-3 text-3xl font-semibold text-white">₹56,640.00</p><div className="mt-5 space-y-3 border-t border-violet-300/10 pt-4 text-xs"><div className="flex justify-between text-zinc-400"><span>Subtotal</span><span>₹48,000.00</span></div><div className="flex justify-between text-zinc-400"><span>CGST + SGST</span><span>₹8,640.00</span></div></div><button type="button" className="mt-6 w-full rounded-xl bg-white px-3 py-2.5 text-sm font-semibold text-zinc-950">Create invoice</button></div></div>; }

function PaymentView() { return <div className="mx-auto grid max-w-2xl gap-4 sm:grid-cols-[1fr_.72fr]"><div className="rounded-2xl border border-white/[.1] bg-white/[.045] p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold tracking-[.14em] text-zinc-500">INVOICE FROM</p><p className="mt-2 text-xl font-semibold text-white">Studio North</p><p className="mt-2 text-xs text-zinc-500">INV-00042 · Due 18 Aug 2026</p></div><span className="rounded-full bg-amber-300/10 px-2.5 py-1 text-xs font-medium text-amber-200">Awaiting payment</span></div><div className="mt-7 space-y-3 border-y border-white/[.08] py-5 text-sm"><div className="flex justify-between text-zinc-300"><span>Product design retainer</span><span>₹48,000</span></div><div className="flex justify-between text-zinc-500"><span>GST · 18%</span><span>₹8,640</span></div></div><div className="mt-5 flex justify-between"><span className="text-sm font-medium text-zinc-400">Amount due</span><span className="text-2xl font-semibold text-white">₹56,640</span></div><button type="button" className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-white py-3 text-sm font-semibold text-zinc-950"><CreditCard className="size-4" />Pay securely by card</button></div><div className="rounded-2xl border border-white/[.08] bg-black/30 p-5 text-center"><p className="text-sm font-semibold text-white">Or pay with UPI</p><div className="mx-auto mt-4 grid size-36 grid-cols-7 gap-1 rounded-xl bg-white p-3">{Array.from({ length: 49 }, (_, index) => <span key={index} className={cn("rounded-[1px]", [0, 1, 2, 4, 6, 7, 8, 9, 14, 16, 18, 20, 21, 22, 23, 24, 26, 28, 30, 31, 32, 33, 35, 37, 39, 40, 41, 42, 44, 46, 48].includes(index) ? "bg-zinc-900" : "bg-white")} />)}</div><QrCode className="mx-auto mt-4 size-5 text-violet-300" /><p className="mt-2 text-xs leading-5 text-zinc-500">Scan with any UPI app.<br />The amount is ready.</p></div></div>; }

function AnalyticsView() { return <div className="rounded-2xl border border-white/[.09] bg-white/[.025] p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-white">Revenue analytics</p><p className="mt-1 text-xs text-zinc-500">The last six months, at a glance.</p></div><div className="flex rounded-lg border border-white/[.08] p-1 text-xs"><span className="rounded-md bg-white/10 px-2.5 py-1.5 text-white">6 months</span><span className="px-2.5 py-1.5 text-zinc-500">12 months</span></div></div><div className="mt-8 grid gap-3 sm:grid-cols-3">{[{ title: "Total billed", value: "₹12.8L" }, { title: "Collected", value: "₹11.4L" }, { title: "Collection rate", value: "89%" }].map((item) => <div key={item.title} className="rounded-xl border border-white/[.07] bg-black/20 p-4"><p className="text-xs text-zinc-500">{item.title}</p><p className="mt-2 text-2xl font-semibold text-white">{item.value}</p></div>)}</div><div className="mt-7 flex h-44 items-end justify-between gap-2 border-b border-white/[.08] px-3">{[34, 46, 41, 63, 52, 76, 69, 84, 59, 88, 72, 100].map((height, index) => <div key={index} className="flex h-full flex-1 items-end gap-0.5"><motion.span initial={{ height: 0 }} animate={{ height: `${height}%` }} transition={{ duration: .45, delay: index * .04 }} className="w-1/2 rounded-t bg-violet-400/90" /><motion.span initial={{ height: 0 }} animate={{ height: `${Math.max(height - 15, 10)}%` }} transition={{ duration: .45, delay: .1 + index * .04 }} className="w-1/2 rounded-t bg-emerald-400/80" /></div>)}</div><div className="mt-4 flex gap-4 text-xs text-zinc-500"><span className="flex items-center gap-2"><i className="size-2 rounded-sm bg-violet-400" />Billed</span><span className="flex items-center gap-2"><i className="size-2 rounded-sm bg-emerald-400" />Collected</span></div></div>; }

export function ProductShowcase() {
  const [active, setActive] = useState<Tab>("dashboard");
  return <section className="relative overflow-hidden py-24 sm:py-32"><div className="marketing-grid absolute inset-x-0 top-0 h-[32rem] opacity-70" /><div className="relative mx-auto max-w-7xl px-5"><div className="max-w-2xl"><p className="marketing-eyebrow">ONE CALM CONTROL ROOM</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.045em] text-white sm:text-5xl">Every money-moving moment, deliberately connected.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-zinc-400">CloudInvoice brings invoice creation, client collection, and revenue visibility into one quiet, capable workspace.</p></div><div className="mt-10 flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="Product views">{tabs.map(({ id, label, icon: Icon }) => <button type="button" key={id} role="tab" aria-selected={active === id} onClick={() => setActive(id)} className={cn("inline-flex shrink-0 items-center gap-2 rounded-xl border px-3.5 py-2.5 text-sm font-medium transition", active === id ? "border-violet-300/30 bg-violet-400/15 text-white" : "border-white/[.08] bg-white/[.025] text-zinc-400 hover:border-white/20 hover:text-zinc-200")}><Icon className="size-4" />{label}</button>)}</div><div className="marketing-glass mt-5 min-h-[31rem] rounded-[1.5rem] p-4 sm:p-6"><AnimatePresence mode="wait"><motion.div key={active} initial={{ opacity: 0, filter: "blur(6px)", y: 8 }} animate={{ opacity: 1, filter: "blur(0px)", y: 0 }} exit={{ opacity: 0, filter: "blur(6px)", y: -8 }} transition={{ duration: .22 }}>{active === "dashboard" && <DashboardView />}{active === "invoice" && <InvoiceView />}{active === "payments" && <PaymentView />}{active === "analytics" && <AnalyticsView />}</motion.div></AnimatePresence></div></div></section>;
}
