import Link from "next/link";
import { FileText, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/status-badge";
import { formatDate, money } from "@/lib/utils";
import { prisma } from "@/lib/prisma";
import { requireOrganization } from "@/lib/organization";

export default async function InvoicesPage() { const organization = await requireOrganization(); const invoices = await prisma.invoice.findMany({ where: { organizationId: organization.id }, include: { client: { select: { name: true } } }, orderBy: { createdAt: "desc" } }); return <main className="mx-auto w-full max-w-7xl p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-muted-foreground">BILLING</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Invoices</h1><p className="mt-2 text-sm text-muted-foreground">Create, send and follow each payment.</p></div><Button asChild><Link href="/invoices/new"><Plus className="size-4" />New invoice</Link></Button></div>{invoices.length === 0 ? <section className="surface mt-8 grid min-h-72 place-items-center rounded-2xl p-8 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-xl bg-muted text-primary"><FileText className="size-6" /></span><h2 className="mt-4 font-semibold">No invoices yet</h2><p className="mt-1 text-sm text-muted-foreground">Turn a finished project into a polished invoice.</p><Button className="mt-5" asChild><Link href="/invoices/new">Create invoice</Link></Button></div></section> : <section className="surface mt-8 overflow-hidden rounded-2xl"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-muted/50 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Invoice</th><th className="px-5 py-3 font-medium">Client</th><th className="px-5 py-3 font-medium">Issued</th><th className="px-5 py-3 font-medium">Due</th><th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3 text-right font-medium">Total</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id} className="border-t hover:bg-muted/30"><td className="px-5 py-4 font-medium"><Link href={`/invoices/${invoice.id}`} className="text-primary underline decoration-primary/35 decoration-2 underline-offset-4 transition hover:decoration-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/40">{invoice.invoiceNumber}</Link></td><td className="px-5 py-4">{invoice.client.name}</td><td className="px-5 py-4 text-muted-foreground">{formatDate(invoice.issueDate)}</td><td className="px-5 py-4 text-muted-foreground">{formatDate(invoice.dueDate)}</td><td className="px-5 py-4"><StatusBadge status={invoice.status} showDot={true} size="sm" /></td><td className="px-5 py-4 text-right font-medium">{money(invoice.total.toString(), invoice.currency)}</td></tr>)}</tbody></table></div></section>}</main>; }
